=== siyer13/xml-avro/student.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="firstname"/>
              <xs:element type="xs:string" name="middlename"/>
              <xs:element type="xs:string" name="lastname"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="dob">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="date"/>
              <xs:element name="month">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="3"/>
						<xs:maxLength value="3"/>
						<xs:pattern value="[A-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element type="xs:short" name="year"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="electives">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="subject" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== siyer13/xml-avro/student.xml
<?xml version="1.0"?>
<student
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="C:/Users/Sridhar/Documents/student.xsd">
	<name>
		<firstname>Sridhar</firstname>
		<middlename>Ramakrishnan</middlename>
		<lastname>Iyer</lastname>
	</name>
	<dob>
		<date>01</date>
		<month>JAN</month>
		<year>2000</year>
	</dob>
	<electives>
		<subject>Physics</subject>
		<subject>Mathematics</subject>
		<subject>Computers</subject>		
	</electives>
</student>
